OPTIONS (SKIP=3, LOAD=1000)


LOAD DATA
INFILE 'order.dat'
REPLACE
INTO TABLE orders
   (ORDERID       TERMINATED BY WHITESPACE,
    CUSTOMERID        TERMINATED BY WHITESPACE,
    SALES_EMP_SSN   TERMINATED BY WHITESPACE,
    ORDER_METHOD TERMINATED BY WHITESPACE
)
    
    


