OPTIONS(SKIP=3, LOAD=1000)
LOAD 
INFILE 'product.dat'
REPLACE 
INTO TABLE product
   (PRODUCTID		TERMINATED BY WHITESPACE,
    PROD_UNIT_PRICE	TERMINATED BY WHITESPACE,
    DESCRIPTION		TERMINATED BY WHITESPACE)
    
    


