OPTIONS (SKIP=3, LOAD=1000)

LOAD DATA
INFILE payment.dat

INTO TABLE payment
   (PAYMENTID 		TERMINATED BY ",",
    ORDERID			TERMINATED BY ",",
    CARD_EXP_DATE		TERMINATED BY ",",
    PAYMENT_AMOUNT	TERMINATED BY ",",
    PAYMENT_METHOD)

