SPOOL tbspace

CREATE TABLESPACE "USER_DATA1" LOGGING
DATAFILE '/u01/app/oracle/oradata/DBST670/user_data01.dbf' SIZE 1500K REUSE
AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE "USER_DATA2" LOGGING
DATAFILE '/u01/app/oracle/oradata/DBST670/user_data02.dbf' SIZE 2000K REUSE
AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

CREATE TABLESPACE "USER_INDX1" LOGGING
DATAFILE '/u01/app/oracle/oradata/DBST670/user_indx01.dbf' SIZE 2000K REUSE
AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL;

SPOOL OFF

